export const EMAIL_ALREADY_IN_USE = 'EMAIL ALREADY IN USE'
export const USER_NOT_FOUND = 'USER NOT FOUND'
export const INVALID_CREDENTIALS = 'INVALID CREDENTIALS'
export const WRONG_EMAIL_OR_PASSWORD = 'WRONG EMAIL OR PASSWORD'
